---
.matlab_defaults:
  image:
    # Replace the value with the name
    # of the MATLAB container image you want to use
    name: mathworks/matlab:latest
    entrypoint: ['']
  variables:
    # Replace the value with the port number
    # and DNS address for your network license manager
    MLM_LICENSE_FILE: 27000@licmatlab.hrz.uni-marburg.de

stages:
- lint
- build
- test

miss_hit:
  stage: lint
  # use a python docker image
  image: python:latest
  script:
  # install miss_hit
  - pip install miss_hit
  # run miss_hit
  - mh_lint
  - mh_style
  - mh_metric --ci

set-up:
  stage: build

  # FIXME
  #
  # cache:
  #   key: $CI_COMMIT_REF_SLUG
  #   paths:
  #   - MOxUnit
  #   - MOcov

  script:
  # install git and get MOcov and MOxUnit
  - apk update && apk add git
  - git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
  - git clone https://github.com/MOcov/MOcov.git --depth 1

# TODO
#
# test:
#   stage: test
#   cache:
#     key: $CI_COMMIT_REF_SLUG
#     paths:
#     - MOxUnit
#     - MOcov
#   extends: .matlab_defaults
#   script:
#   - matlab -batch mycommand
