---
# Project information
site_name: 'Clean code workshop: MATLAB'
repo_name: Remi-Gau/matlab_clean_code_workshop
repo_url: https://github.com/Remi-Gau/matlab_clean_code_workshop
# docs_dir: alternative_path # docs/ is the default folder
copyright: CC-BY-4.0

# This will use Material them
theme:
  name: material
  language: en
  palette:
    primary: deep orange
    accent: cyan

docs_dir: doc

# Pages
nav:
- Welcome: index.md
- 1 - Testing: part_1.md
- 2 - Formatting: part_2.md
- 3 - Refactoring: part_3.md
- 4 - Automating: part_4.md

# list of extension
markdown_extensions:
- admonition
- pymdownx.details
- toc:
    anchorlink: true
- pymdownx.superfences
