function set_axis()
    % (C) Copyright 2023 Remi Gau
    axis('tight');
    set(gca, ...
        'tickdir', 'out', ...
        'ticklength', [0.005 0], ...
        'fontsize', 12, ...
        'ylim', [0 1]);
end
